# =========================================================
# PayCore - Development Configuration
# =========================================================

spring.application.name=${APP_NAME:PayCore}
server.port=${SERVER_PORT:9099}


# =========================================================
# PostgreSQL
# =========================================================

spring.datasource.url=jdbc:postgresql://${PAYCORE_DB_HOST:localhost}:${PAYCORE_DB_PORT:5432}/${PAYCORE_DB_NAME:paycore}
spring.datasource.username=${PAYCORE_DB_USERNAME:paycore}
spring.datasource.password=${PAYCORE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# Connection Pool - HikariCP
# =========================================================

spring.datasource.hikari.pool-name=PayCoreHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# =========================================================
# Redis
# =========================================================

spring.data.redis.host=${PAYCORE_REDIS_HOST:localhost}
spring.data.redis.port=${PAYCORE_REDIS_PORT:6379}
spring.data.redis.timeout=2000ms


# =========================================================
# Kafka
# =========================================================

spring.kafka.bootstrap-servers=${PAYCORE_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:paycore-dev}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3


# =========================================================
# Logging
# =========================================================

logging.level.root=INFO
logging.level.com.banking.bank=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO


# =========================================================
# PayCore Application Settings
# =========================================================

paycore.security.jwt.access-token-expiration=${PAYCORE_JWT_ACCESS_TOKEN_EXPIRATION:15m}
paycore.security.jwt.refresh-token-expiration=${PAYCORE_JWT_REFRESH_TOKEN_EXPIRATION:7d}

paycore.payment.max-amount=${PAYCORE_MAX_PAYMENT_AMOUNT:10000}

paycore.webhook.signature-algorithm=${PAYCORE_WEBHOOK_SIGNATURE_ALGORITHM:HmacSHA256}
