spring.application.name=PayCore
server.port=9099

# Active Enviroment
spring.profiles.active=dev

# Common JPA Configuration
spring.jpa.open-in-view=false

# Common Application Settings
# Jackson 3 moved this option from SerializationFeature to DateTimeFeature.
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

# Logging
logging.level.root=INFO
logging.level.com.banking.bank=INFO
